name: ml
channels:
    - conda-forge
dependencies:
    - python=3
    - numpy
    - matplotlib
    - pandas
    - scikit-learn=0.18.1
    - theano
    - tensorflow
    - lasagne
    - keras
    - jupyter
    - pip:
      - xgboost
      - hep_ml
