name: py2root5
channels:
    - conda-forge
    - nlesc
dependencies:
    - python=2
    - root=5
    - root-numpy
    - root_pandas
    - numpy
    - matplotlib=2.*
    - pandas
    - scikit-learn
    - theano
    - tensorflow
    - lasagne
    - jupyter
    - pip
