name: py2root6
channels:
    - nlesc
dependencies:
    - python=2
    - root=6
    - numpy
    - root-numpy
    - matplotlib
    - pandas
    - scikit-learn
    - jupyter
    - pip:
      - root_pandas
      - seaborn
