name: py3root6
channels:
    - conda-forge
    - nlesc
dependencies:
    - python=3
    - root=6
    - root-numpy
    - root_pandas
    - numpy
    - matplotlib=2.*
    - pandas
    - scikit-learn
    - theano
    - tensorflow
    - lasagne
    - jupyter
    - pip
